### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by borpin** [andrewjfreyer/monitor#34] opened 2018-09-29 18:13 UTC
I am seeing a gradual rise in memory usage.

The Pi it is installed on is a DietPi base image that only runs Monitor.

On boot this is what I see in htop:

![image](https://user-images.githubusercontent.com/1322749/46249088-13ca8280-c41b-11e8-9ea8-1b2a0047bf44.png)

After a while (you can see the up time, memory use by one of the monitor processes has risen significantly.

![image](https://user-images.githubusercontent.com/1322749/46249067-a0287580-c41a-11e8-8802-81afb461bb12.png)

BTW, why are there so many processes?

I also note that the CPU use regularly maxes out.

**Comment by andrewjfreyer** [comment] 2018-09-29 20:33
Memory requirements will increase over time as more devices are seen and recorded by `monitor`. One of the reasons for this is expiration biasing logic, which on further consideration I'm planning to remove. 

The reason for the number of processes is to increase performance via forking certain tasks that do not need to be serially run. .

**Comment by borpin** [comment] 2018-09-30 05:46
Hi Andrew, 

How much does the -c option clear the memory used?

Could you offer an option to 'flush' the (unknown) devices held in memory perhaps on a specified schedule (although that could be automated externally)?  I have not run Monitor for  a long enough period of time to be sure, but I suspect that it is not stable long term as it will run out of memory.

Cheers

Brian

**Comment by andrewjfreyer** [comment] 2018-09-30 14:48
That flag deletes two hidden files, that’s it.

**Comment by andrewjfreyer** [comment] 2018-10-24 14:10
Although 75% usage still seems high, I believe the source of a memory leak is unbounded growth of the process table.  I have sprinkled a few `disown` throughout, since I’m using fifos anyway.  See what you think on the beta branch.

**Comment by borpin** [comment] 2018-10-24 20:15
Still a huge amount of memory and eventually it will run out. I've moved to a simpler solution for now because of this issue.

Do you not see the memory use growing?

Cheers

**Comment by andrewjfreyer** [comment] 2018-10-25 22:02
are you confirming the issue on beta? i do not see the growth youve reported

**Comment by andrewjfreyer** [comment] 2018-10-26 17:59
After leaving an instance of monitor open for 14 hours in a noisy bluetooth environment, I did notice memory increasing. I've narrowed the cause down to the BTLE listener that processes packets. Working on a solution and fix. 

Thanks for the report!

**Comment by andrewjfreyer** [comment] 2018-10-30 14:47
Fixed as of 0.1.691

**Closed by andrewjfreyer** 2018-10-30 14:47 UTC
Labels: bug
