### ISSUE TITLE
environment (-e) mqtt payload is malformed

### ISSUE THREAD

**Issue by Phileep** [andrewjfreyer/monitor#19] opened 2018-09-08 03:50 UTC
I am using 0.1.587 with the -e flag

In my mqtt broker, the only payload I get is {
looks like it is not completing the build of the payload before publishing

Other mqtt messages are arriving fine from monitor

I am running on a Pi 3 which is using ethernet to connect to the TCP/IP network (ie not using wifi).

**Comment by andrewjfreyer** [comment] 2018-09-08 06:01
Thanks. I’ll look into this.

**Comment by hmmbob** [comment] 2018-09-08 14:26
Oh, I was just about to open an issue for this too. I am using Wifi though, on a Pi Zero W.

While fiddling around to see if I could solve it, I changed `env_message="{ generic ` to `env_message="{generic `. That gave me {generic is payload, opposite to just the {.

I lack knowledge to see what the issue is, but maybe this helps you tracking the issue down.

**Comment by andrewjfreyer** [comment] 2018-09-08 15:01
Fixed on 0.1.598. Closing for now.

**Closed by andrewjfreyer** 2018-09-08 15:01 UTC
