### ISSUE TITLE
MQTT with no username not connecting (was in previous version)

### ISSUE THREAD

**Issue by Klagio** [andrewjfreyer/monitor#151] opened 2019-03-14 13:20 UTC
@andrewjfreyer Hi,  just upgraded to 0.2.053 but having big issue, not connecting to mqtt broker. I have no user and no password in my mqtt

    ================== BEGIN LOGGING ==================
    Connection Refused: not authorised.
    Error: The connection was refused.
    0.2.053 14-03-2019 12:58:05 pm [CMD-ERRO]       mqtt broker went offline, or a p                                 assword/username combination was rejected. attempting subscribe in 10 seconds...

this the log in HASSIO mosquitto 

    1552568448: New connection from 192.168.1.237 on port 1883. 1552568448: Socket error on client &lt;unknown&gt;, disconnecting.

this my mqtt_preferences, which were working in previous version (I did not update since long)

    # IP ADDRESS OR HOSTNAME OF MQTT BROKER
    mqtt_address=192.168.1.11

    # MQTT BROKER USERNAME (OR BLANK FOR NONE)
    mqtt_user=""

    # MQTT BROKER PASSWORD (OR BLANK FOR NONE)
    mqtt_password=""

 
tried also  as below but same error

    mqtt_user=
    mqtt_password=

tried also 
```

mqtt_user=''
mqtt_password=''
```

**Comment by Klagio** [comment] 2019-03-14 13:22
I have around 50 devices now programmed like this, for me to change all of them including a username/password is a big headache (a couple of devices will need to dismount to put in flash mode and so on)

**Comment by Klagio** [comment] 2019-03-14 14:49
Updated to HASSIO Mosquitto 4.1, but problem persist

this the addon config
```

{
  "logins": [
    {
      "username": "",
      "password": ""
    }
  ],
  "anonymous": true,
  "customize": {
    "active": true,
    "folder": "mosquitto"
  },
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem"
}
```
this in  /usr/share/hassio/share/mosquittoacl.conf
`
acl_file /share/mosquitto/accesscontrollist
`
this in  /usr/share/hassio/share/mosquitto/accesscontrollist
`
topic readwrite #`

**Comment by Klagio** [comment] 2019-03-14 14:52
this is the HASSIO addon initial log
```

[INFO] Setup mosquitto configuration
[INFO] Found local users inside config
[INFO] Initialize Hass.io Add-on services
[INFO] Initialize Home Assistant discovery
[INFO] Start Mosquitto daemon
1552575113: mosquitto version 1.5.6 starting
1552575113: Config loaded from /etc/mosquitto.conf.
1552575113: |-- *** auth-plug: startup
1552575113: |-- ** Configured order: http

1552575113: |-- with_tls=false
1552575113: |-- getuser_uri=/login
1552575113: |-- superuser_uri=/superuser
1552575113: |-- aclcheck_uri=/acl
1552575113: |-- getuser_params=(null)
1552575113: |-- superuser_params=(null)
1552575113: |-- aclcheck_params=(null)
1552575113: |-- retry_count=3
1552575113: Opening ipv4 listen socket on port 1883.
1552575113: Opening ipv6 listen socket on port 1883.
1552575113: Opening websockets listen socket on port 1884.
1552575113: Opening ipv4 listen socket on port 8883.
1552575113: Opening ipv6 listen socket on port 8883.
1552575113: Opening websockets listen socket on port 8884.
1552575113: Warning: Mosquitto should not be run as root/administrator.
1552575113: New connection from 172.30.32.1 on port 1883.
1552575113: New client connected from 172.30.32.1 as appdaemon_mqtt_client (c1, k60).
```

**Comment by andrewjfreyer** [comment] 2019-03-14 17:35
Other users have reported this as well, I'm still working out the best way to address it. Your test of

```bash
sudo mosquitto_sub -h "192.168.1.11" -u "" -P "" -t "#" 
Connection Refused: not authorised.
```

...shows the problem is with blank usernames and passwords. You can set a username and password and continue to allow anonymous posting in the interim.

**Comment by Klagio** [comment] 2019-03-14 17:46
No because I have some esp8266 that I can't reflash easily, already programmed with blank username and password

**Comment by Klagio** [comment] 2019-03-14 17:49
I tried to add another login with a non blank username and password but it gave tons of error

**Comment by Klagio** [comment] 2019-03-14 17:55
I put test as username and password in monitor mqtt_preferences

1552586032: New connection from 192.168.1.238 on port 1883.
1552586032: |-- mosquitto_auth_unpwd_check(test)
1552586032: |-- ** checking backend http
1552586032: |-- url=http://127.0.0.1:8080/login
1552586032: |-- data=username=test&password=test&topic=&acc=-1&clientid=
1552586032: |-- http req fail url=http://127.0.0.1:8080/login re=Couldn't connect to server
1552586032: |-- url=http://127.0.0.1:8080/login
1552586032: |-- data=username=test&password=test&topic=&acc=-1&clientid=
1552586032: |-- http req fail url=http://127.0.0.1:8080/login re=Couldn't connect to server
1552586032: |-- url=http://127.0.0.1:8080/login
1552586032: |-- data=username=test&password=test&topic=&acc=-1&clientid=
1552586032: |-- http req fail url=http://127.0.0.1:8080/login re=Couldn't connect to server
1552586032: |-- url=http://127.0.0.1:8080/login
1552586032: |-- data=username=test&password=test&topic=&acc=-1&clientid=
1552586032: |-- http req fail url=http://127.0.0.1:8080/login re=Couldn't connect to server
1552586032: |-- getuser(test) AUTHENTICATED=0 by none
1552586032: |-- getuser(test) AUTHENTICATED=N HAS_ERROR=Y => ERR_UNKNOWN

**Comment by Klagio** [comment] 2019-03-14 19:04
I know put the usernmae test and password test both in HASSIo addon configuration and in mqtt_preferences, another error, strange, I don't understand
```

{
  "logins": [
    {
      "username": "test",
      "password": "test"
    }
  ],
  "anonymous": true,
  "customize": {
    "active": true,
    "folder": "mosquitto"
  },
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem"
}


```
```

1552590143: New connection from 192.168.1.238 on port 1883.
1552590143: |-- mosquitto_auth_unpwd_check(test)
1552590143: |-- ** checking backend http
1552590143: |-- url=http://127.0.0.1:8080/login
1552590143: |-- data=username=test&password=test&topic=&acc=-1&clientid=
[INFO] found test on local database
1552590143: |-- getuser(test) AUTHENTICATED=1 by http
1552590143: Socket error on client <unknown>, disconnecting.
1552590144: New connection from 192.168.1.238 on port 1883.
1552590144: |-- mosquitto_auth_unpwd_check(test)
1552590144: |-- ** checking backend http
1552590144: |-- url=http://127.0.0.1:8080/login
1552590144: |-- data=username=test&password=test&topic=&acc=-1&clientid=
[INFO] found test on local database
1552590145: |-- getuser(test) AUTHENTICATED=1 by http
1552590145: Socket error on client <unknown>, disconnecting.
1552590145: New connection from 192.168.1.188 on port 1883.
1552590145: New connection from 192.168.1.189 on port 1883.
1552590145: New client connected from 192.168.1.189 as 14b_DoorLock (c1, k15).
1552590145: New client connected from 192.168.1.188 as 14a_DoorLock (c1, k15).
1552590145: New connection from 192.168.1.186 on port 1883.
1552590145: Socket error on client <unknown>, disconnecting.
1552590146: New connection from 192.168.1.238 on port 1883.
1552590146: |-- mosquitto_auth_unpwd_check(test)
1552590146: |-- ** checking backend http
1552590146: |-- url=http://127.0.0.1:8080/login
1552590146: |-- data=username=test&password=test&topic=&acc=-1&clientid=
[INFO] found test on local database
1552590146: |-- getuser(test) AUTHENTICATED=1 by http
1552590146: Socket error on client <unknown>, disconnecting.
1552590147: New connection from 192.168.1.238 on port 1883.
1552590147: |-- mosquitto_auth_unpwd_check(test)
1552590147: |-- ** checking backend http
1552590147: |-- url=http://127.0.0.1:8080/login
1552590147: |-- data=username=test&password=test&topic=&acc=-1&clientid=
[INFO] found test on local database
1552590147: |-- getuser(test) AUTHENTICATED=1 by http
1552590147: Socket error on client <unknown>, disconnecting.
```

**Comment by DubhAd** [comment] 2019-03-14 21:17
> Other users have reported this as well, I'm still working out the best way to address it. 

I see the same thing. IMO the [same approach](https://github.com/andrewjfreyer/monitor/blob/master/support/setup#L74) as you're using for handling the MQTT version, and CA, makes sense. Obviously better if us lazy folks require auth ;)

**Comment by andrewjfreyer** [comment] 2019-03-14 21:23
The issue with this strategy is passwords with special characters and/or spaces in passwords. There's some strange escaping handling that goes on in mosquitto_pub/_sub that doesn't like this technique for passwords... 

Tried it a few months ago, and users with spaces in particular were struggling. 

I probably did something stupid with escaping, but that's my own fault for letting a small bash script get so far out of hand that it's a few thousand lines of code. sigh...

**Comment by kylerw** [comment] 2019-03-15 20:29
I'm seeing this same behavior using user/pass that was working previously

**Comment by andrewjfreyer** [comment] 2019-03-16 02:21
This should be fixed in the most recent push. Tested on my end and the new strategy is working for passwords and usernames with special characters, simpler passwords and usernames, and blank passwords and usernames. Please comment if this does not correct your issues.

**Closed by andrewjfreyer** 2019-03-16 02:21 UTC

**Comment by mariusmotea** [comment] 2021-02-10 08:36
Annoing feature. An all test vm's i need now to create vimrc in order to be able to paste in INSERT mode.

**Comment by lewisward1** [comment] 2023-04-17 21:06
Hi - I just setup a pi zero with monitor to sense when the phones are home - i am getting the [CMD-MQTT]	warning: mqtt broker refused connection - check username, password, and host address  error - any help please ?
