### ISSUE TITLE
Not getting iphone confidence level

### ISSUE THREAD

**Issue by gbdavidx** [andrewjfreyer/monitor#162] opened 2019-03-26 02:26 UTC
MQTT logs...

1553566768: |-- mosquitto_auth_acl_check(..., client id not available, mosquitto, monitor/downstairs/9C:E6:5E:0B:4B:C9/rssi, MOSQ_ACL_WRITE)
1553566768: |-- aclcheck(mosquitto, monitor/downstairs/9C:E6:5E:0B:4B:C9/rssi, 2) CACHEDAUTH: 0
1553566768: Client downstairs6754 disconnected.

I am not sure what this means, i am sure it is not monitor, but i set it up as directed, but no values are coming through, i have a username/password setup in monitor, but keep getting this acl check, i have another module for my ring alarm that works fine to control my alarm panel (ring.com), so i don't think its an issue with my ring

sensor.downstairs | unknown | unit_of_measurement: % friendly_name: Downstairs
-- | -- | --

```
My sensors.yaml file:
  - platform: mqtt
    state_topic: 'monitor/downstairs/9C:E6:5E:0B:4B:C9'
    value_template: '{{ value_json.confidence }}'
    unit_of_measurement: '%'
    name: 'Downstairs'
```

```
david@raspberrypi:/etc/apt/sources.list.d/monitor$ sudo bash monitor.sh -t[adr]

===================================================

              *** BETA/DEV BRANCH ***

===================================================
> starting monitor.sh (v. 0.2.148)...
> warning: unknown trigger mode: [adr]
> 9C:E6:5E:0B:4B:C9 confidence topic: monitor/downstairs { id: 9C:E6:5E:0B:4B:C9 ... } (has previously connected to hci0)
> E4:E4:AB:80:14:92 confidence topic: monitor/downstairs { id: E4:E4:AB:80:14:92 ... } (has not previously connected to hci0)
[-] 0.2.148 25-03-2019 06:54:35 PM [CMD-INFO]	**** started arrival scan [x1 max rep] **** 
[-] 0.2.148 25-03-2019 06:54:39 PM [CMD-POST]	monitor/downstairs/9C:E6:5E:0B:4B:C9
[-] 0.2.148 25-03-2019 06:54:43 PM [CMD-NAME]	9C:E6:5E:0B:4B:C9 David’s iPhone  Apple Inc
[-] 0.2.148 25-03-2019 06:54:47 PM [CMD-POST]	monitor/downstairs/E4:E4:AB:80:14:92
[-] 0.2.148 25-03-2019 06:54:47 PM [CMD-NAME]	E4:E4:AB:80:14:92 David’s Apple Watch  Apple Inc
[-] 0.2.148 25-03-2019 06:54:49 PM [CMD-INFO]	**** completed arrival scan **** 
[-] 0.2.148 25-03-2019 06:55:40 PM [CMD-RSSI]	PUBL 78:9C:85:04:50:55 RSSI: -75 dBm (initial reading | 125 dBm) 
[-] 0.2.148 25-03-2019 06:55:43 PM [CMD-RSSI]	PUBL B0:C0:90:8D:4B:DB RSSI: -78 dBm (initial reading | 122 dBm) 
Can't create connection: Input/output error
```
I am in a docker container running hassio (with mqtt broker installed in the add-ons section) on top of Ubuntu

**Comment by gbdavidx** [comment] 2019-03-26 03:42
RSSI also doesn't seem accurate...? what is the formular, why doesn't it move from -99 if i move it 4 feet away, i would think it would drop to -60ish rssi

**Comment by andrewjfreyer** [comment] 2019-03-26 15:01
Note the logs here, you're using incorrect flags. The brackets in the `-t` argument are causing the error. If you want to trigger arrival and depart scans only, you would use `-tadr` without brackets - the brackets in the log show that the `adr` options are optional. 

Second, the logs show that you are successfully connecting to and publishing to your broker. 

Third, the logs show that you're using single topic mode. We can see from the initial boot logging that monitor is posting to `monitor/downstairs` for each of your devices. 

Restore to default settings with `-d` and try again. 

Lastly, if you review the forum and the documentation, you'll see that RSSI *isn't* an accurate predictor of distance at all. Monitor is just reporting the value that your bluetooth hardware outputs. There is no formula. Rssi, by its nature, is a very noisy measurement. It is provided as additional data, but it can't and shouldn't be relied on as any sort of presence indicator. That's why monitor outputs confidence and not rssi by default. 

Since monitor is showing expected behavior here, I'm closing this issue. Please update this thread if you continue to experience issues after reviewing the documentation and restoring default settings.

**Closed by andrewjfreyer** 2019-03-26 15:01 UTC

**Comment by gbdavidx** [comment] 2019-03-27 02:17
david@raspberrypi:/etc/apt/sources.list.d/monitor$ sudo bash monitor.sh -tar

===================================================

              *** BETA/DEV BRANCH ***

===================================================
> starting monitor.sh (v. 0.2.148)...
> 9C:E6:5E:0B:4B:C9 confidence topic: monitor/downstairs { id: 9C:E6:5E:0B:4B:C9 ... } (has previously connected to hci0)
i just reset this from my pi zero and now it doesn't do anything...?

**Comment by andrewjfreyer** [comment] 2019-03-27 18:03
You're using the arrival trigger flag - so nothing will happen until you *trigger* an arrival scan via mqtt. Please review the documentation to understand how monitor works.
