### ISSUE TITLE
Problem when starting monitor

### ISSUE THREAD

**Issue by 03397** [andrewjfreyer/monitor#114] opened 2019-02-14 06:58 UTC
I have the latest version and monitor starts successfully. 
After a while I am getting a timeout error. 
When i stop a monitor and issue a hcitool lescan I am getting
Could not create connection: Input/output error.

In order to resolve the issue I need do a hciconfig hci0 down and hciconfig hci0 up.
After I restart the monitor.sh the problem appears again

**Comment by 03397** [comment] 2019-02-14 16:08
More info
root@raspberrypi:/home/pi/scripts/monitor# bash monitor.sh
====================== DEBUG ======================
starting monitor.sh (v. 0.2.002)…

removing web request caches
removing public name cache
preference: using mqtt protocol version mqttv311
preference: minimum time between the same type of scan = 15
preference: regex filter for flags to accept = .*
preference: regex filter for flags to reject = NONE
preference: regex filter for manufacturers to accept = .*
preference: regex filter for manufacturers to reject = NONE
preference: maximum sequential arrive scan attempts = 1
preference: maximum sequential depart scan attempts = 2
preference: selected HCI device = hci0
mqtt trigger: monitor/scan/ARRIVE
mqtt trigger: monitor/scan/DEPART
AC:37:43:D4:2F:4B publishes to: monitor/hass/AC:37:43:D4:2F:4B (has not previously connected to hci0)
00:3D:E8:8A:76:D7 publishes to: monitor/hass/00:3D:E8:8A:76:D7 (has not previously connected to hci0)
================== BEGIN LOGGING ==================
0.2.002 05:56:05 pm [CMD-RAND] [passed filter] data: 53:FD:6A:76:0D:7F pdu: ADV_SCAN_IND rssi: -72 dBm flags: none man: unknown delay: 0
0.2.002 05:56:06 pm [CMD-INFO] **** started arrival scan. [x1 max rep] ****
0.2.002 05:56:07 pm [CMD-SCAN] (No. 1) AC:37:43:D4:2F:4B arrival?
0.2.002 05:56:08 pm [CMD-NAME] AC:37:43:D4:2F:4B Nicolas - Pixel XL HTC Corporation
monitor/hass/AC:37:43:D4:2F:4B
{
“id”:“AC:37:43:D4:2F:4B”,
“confidence”:“100”,
“name”:"NicolasPhone ",
“manufacturer”:“HTC Corporation”,
“type”:“KNOWN_MAC”,
“retained”:“false”,
“timestamp”:“Thu Feb 14 2019 17:56:08 GMT+0200 (EET)”,
“version”:“0.2.002”
}

Error: Connection timed out
oot@raspberrypi:/home/pi/scripts/monitor# hcitool lescan
Set scan parameters failed: Input/output error

root@raspberrypi:/home/pi/scripts/monitor# hciconfig hci0 down
root@raspberrypi:/home/pi/scripts/monitor# hciconfig hci0 up
root@raspberrypi:/home/pi/scripts/monitor# hcitool lescan
LE Scan …
5E:49:42:CE:7B:D6 (unknown)
5E:49:42:CE:7B:D6 (unknown)
5E:49:42:CE:7B:D6 (unknown)
5E:49:42:CE:7B:D6 (unknown)
5E:49:42:CE:7B:D6 (unknown)
5E:49:42:CE:7B:D6 (unknown)
5E:49:42:CE:7B:D6 (unknown)
5E:49:42:CE:7B:D6 (unknown)
5E:49:42:CE:7B:D6 (unknown)
5E:49:42:CE:7B:D6 (unknown)
5E:49:42:CE:7B:D6 (unknown)

**Comment by andrewjfreyer** [comment] 2019-02-14 16:53
Per my comment in the HA forums, do you have a bluetooth dongle perhaps?

**Comment by andrewjfreyer** [comment] 2019-02-15 03:32
Confirmed the issue is related to a dongle that does not properly restrict reports of duplicates. Closing as unrelated to monitor.

**Closed by andrewjfreyer** 2019-02-15 03:32 UTC
