### ISSUE TITLE
PREF_DEVICE_TRACKER_REPORT doesn't seem to do anything?

### ISSUE THREAD

**Issue by lancelon** [andrewjfreyer/monitor#296] opened 2020-02-05 20:50 UTC
I've added 

`PREF_DEVICE_TRACKER_REPORT="TRUE"
`
and also tried

`PREF_DEVICE_TRACKER_REPORT=TRUE`

to the bottom of `behavior_preferences ` and even updated to the beta branch, but when listening on `monitor/#` I get all the usual confidence reports for my two tracked devices, but NO device_tracker `'monitor/first floor/[device address or alias]/device_tracker'` type messages come in.

Anything else I can try?

I would post a Monitor version number but I haven't a clue where to find it.

P.S. Monitor is clever software. Am I right it automatically restarts following a save of the behaviour preferences file?

**Comment by andrewjfreyer** [comment] 2020-02-06 19:44
your version matters quite a bit here, but its easy to find. either open the main monitor.sh file and look at the variable directly or run from the command line and you'll see it there. the version number is also reported in almost all mqtt messages.

**Comment by lancelon** [comment] 2020-02-10 12:05
Sorry for the delay. I've checked my version, it's  version": "0.2.200"

**Comment by johntdyer** [comment] 2020-02-18 19:49
Same issue here

I've tried "true" / true / TRUE and "TRUE"

**Comment by lancelon** [comment] 2020-02-27 09:00
hmmm, odd

**Comment by andrewjfreyer** [comment] 2020-02-27 21:30
Have you changed your $mqtt_topicpath?

**Comment by lancelon** [comment] 2020-02-28 09:55
no, and if I request a reset or an echo that works, so I guess that suggests the $mqtt_topicpath is functioning as normal?

**Comment by andrewjfreyer** [comment] 2020-02-28 18:30
Hmm... I'm not able to reproduce on my end. In your mqtt preferences file, you have: 

```
PREF_DEVICE_TRACKER_REPORT=true
```

?

**Comment by lancelon** [comment] 2020-02-28 20:37
At the moment I have 
`PREF_DEVICE_TRACKER_REPORT="TRUE"`
but as I said I've tried just `TRUE` but will try lower case true without quotation marks and report back

**Comment by andrewjfreyer** [comment] 2020-03-29 17:20
Closing for now, if you have continued issues feel free to reopen

**Closed by andrewjfreyer** 2020-03-29 17:20 UTC
Labels: more information needed

**Comment by lancelon** [comment] 2021-01-12 19:37
Hi Andrew,
I've still got this issue I'm afraid. @johntdyer do you have it too, still?
Weirdly I found I didn't get any RSSI info until I added my MAC addresses to known_static, previously they were just in known_beacon. After that I started getting RSSI information but never any messages to a device_tracker topic.
Going to try deleting monitor and recloning.

**Comment by lancelon** [comment] 2021-01-12 20:11
Deleting and recloning did the trick, I'm now getting device_tracker messages ...however monitor is currently refusing to find my two iTags. It's just hanging at 

> known beacon: FC:51:FA:29:A1:35 publishes to: monitor/raspberrypi/ronald
> known beacon: FC:51:FA:2B:28:32 publishes to: monitor/raspberrypi/estelle
