### ISSUE TITLE
node stops detecting until monitor/scan/restart called again

### ISSUE THREAD

**Issue by matajumotors** [andrewjfreyer/monitor#301] opened 2020-02-22 19:27 UTC
Hi,
I have two pi zero nodes detecting several phone Bluettoth. It works fine for some days departure scan is initiated on door closures, arriving phones are detected. But then one of two nodes (randomly) stop detecting any devices arriving. I have to publish monitor/scan/restart for stopped node to detect anything again.
publishing monitor/scan/arrive did not do anything, only /restart helped.
What can I check?

**Comment by andrewjfreyer** [comment] 2020-02-23 16:38
The first thing to check is your power supply for the pi. If you have unreliable power, it won't run 24-7 very reliably. What version of `monitor` are you running?

**Comment by matajumotors** [comment] 2020-02-23 17:40
Hi looking at the monitor.sh I am running 0.2.200 .
Regarding the power I thought Pi zero W does not take more than 250mA, I use 2A adapter.
And after reboot, shouldn't the monitor start automatically and do a scan? 
What can I check when/if this happens again, can I see up-time or some log info?

**Comment by matajumotors** [comment] 2020-02-28 00:03
Well tonight both nodes stopped again at different times. Both were not accesible using ssh but were connected to wifi and responded to pings.
After issuing /monitor/scan/restart both were sending mqtt messages and become responsive over ssh, but did not detect any devices..
Sending /arrive or /depart did not help.

Power cycling restored normal operation.

Any thoughts?

**Comment by andrewjfreyer** [comment] 2020-02-28 18:32
Any logs that you can provide would be helpful.

**Comment by riggs498** [comment] 2020-03-22 13:56
I have been using presence for the longest time. With good and bad success. But anyways, here is the error I am getting on my raspberry pi 3 running monitor.
Mar 22 08:18:53 hassbian bash[23467]: ./support/btle: line 352: printf: write error: Broken pipe
Mar 22 08:31:35 hassbian bash[23467]: ./support/btle: line 399: printf: write error: Broken pipe
Mar 22 08:55:04 hassbian bash[23467]: ./support/btle: line 399: printf: write error: Broken pipe
Mar 22 08:56:31 hassbian bash[23467]: ./support/btle: line 399: printf: write error: Broken pipe
If I restart it will work for a few minutes and then this happens again.

**Comment by andrewjfreyer** [comment] 2020-03-29 17:17
Dupe of #236

**Closed by andrewjfreyer** 2020-03-29 17:17 UTC
Labels: more information needed
